# Generated by Django 2.2 on 2021-06-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='provider',
            field=models.CharField(choices=[('DHL', 'DHL'), ('UPS', 'UPS'), ('TNT', 'TNT')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='country',
            name='provider',
            field=models.CharField(choices=[('DHL', 'DHL'), ('UPS', 'UPS'), ('TNT', 'TNT')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='price',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
