# Generated by Django 2.2 on 2021-06-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210628_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='zone',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
