# Generated by Django 2.2 on 2021-06-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210628_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='service',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='price',
            name='service',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='zone',
            field=models.IntegerField(),
        ),
    ]
