# Generated by Django 2.2 on 2021-06-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210628_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='service',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='price',
            name='service',
            field=models.CharField(max_length=100),
        ),
    ]
