# Generated by Django 2.2 on 2021-07-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210628_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surcharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('provider', models.CharField(choices=[('DHL', 'DHL'), ('UPS', 'UPS'), ('TNT', 'TNT')], max_length=3)),
                ('service', models.CharField(choices=[('DHL - time definite', 'DHL - time definite'), ('DHL day definite', 'DHL - day definte')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='country',
            name='service',
            field=models.CharField(choices=[('DHL - time definite', 'DHL - time definite'), ('DHL day definite', 'DHL - day definte')], max_length=100),
        ),
        migrations.AlterField(
            model_name='price',
            name='service',
            field=models.CharField(choices=[('DHL - time definite', 'DHL - time definite'), ('DHL day definite', 'DHL - day definte')], max_length=100),
        ),
    ]
