# Generated by Django 2.2 on 2021-07-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210702_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='service',
            field=models.CharField(choices=[('DHL express worldwide', 'DHL express worldwide'), ('DHL economy select', 'DHL economy select')], max_length=100),
        ),
        migrations.AlterField(
            model_name='price',
            name='service',
            field=models.CharField(choices=[('DHL express worldwide', 'DHL express worldwide'), ('DHL economy select', 'DHL economy select')], max_length=100),
        ),
        migrations.AlterField(
            model_name='surcharge',
            name='service',
            field=models.CharField(choices=[('DHL express worldwide', 'DHL express worldwide'), ('DHL economy select', 'DHL economy select')], max_length=100),
        ),
    ]
